### ISSUE TITLE
Do „Assay Name“ and „Raw Data File“ belong to Phenotyping Protocol ?

### ISSUE THREAD

**Issue by arendd** [MIAPPE/ISA-Tab-for-plant-phenotyping#11]
Sorry for the bunch of questions, but I currently try to prepare a nearly full example dataset that fulfil the MIAPPE 1.1. recommendations. 
I’m a bit confused about the columns „Assay Name“ and „Raw Data File“, because in the documentation it looks like that they belong to the Phenotyping protocol. Is this correct or is it just a misunderstanding? 

Because we currently also developing a comprehensive and powerful Java API for generating ISA-Tab files programmatically and that’s why I thought that in general all ASSAY files have to contain these two columns independent from any protocol!? So this is important, because it would influence the position of the columns within the ASSAY file…

**Comment by PapoutsoglouE** [comment]
In case anyone looks for this information in the future:
The Assay Name and the Raw Data File do not belong to the Phenotyping protocol per se. They are not its parameters. But they are part of the Assay file, and the columns should always be there.
