### ISSUE TITLE
Fields that should not be required

### ISSUE THREAD

**Issue by bedroesb** [MIAPPE/ISA-Tab-for-plant-phenotyping#12]
### In the investigation file:

- Investigation Person Address
- Study Protocol Description
- Study Protocol URI
- Study Protocol Version
- Study Protocol Parameters Name

### In the assay file:

- Parameter Value[Collection Date]
- Parameter Value[Sample Description] 
- Raw Data File

**Comment by PapoutsoglouE** [comment]
The two fields referring to samples in the assay file are now marked as non-mandatory.  
The raw data file column is mandatory, but should be filled in with `NA` if no such files are provided.

About the investigation file:  
* The [Person Address](https://github.com/MIAPPE/ISA-Tab-for-plant-phenotyping/tree/v1.1#investigation-contacts-section) is actually mandatory, and should point to the address of the institute a contact is affiliated with.
* Fixed the protocol URI, description, version and parameter name. Do note that *some are mandatory* [in some cases](https://github.com/MIAPPE/ISA-Tab-for-plant-phenotyping/tree/v1.1#study-protocols-section) fields are also mandatory.
