### ISSUE TITLE
How to handle empty/not available environmental parameter?

### ISSUE THREAD

**Issue by arendd** [MIAPPE/ISA-Tab-for-plant-phenotyping#5]
In the first MIAPPE version the list of environmental parameters was much shorter than in version 1.1. In the configuration for MIAPPE 1.0 more or less all parameters in all protocols were mandatory (“is-required=”true”), but now in version 1.1 we have nearly 50 parameters. In the first draft for the configuration 1.1 the two examples for environmental parameters are optional (“is-required=”false”). Should we assume, that in general all environmental parameters are optional? Otherwise there will be in many use case a lot of empty columns in the study files!?

**Comment by PapoutsoglouE** [comment]
Yes: all environment parameters are optional! Of course, you are strongly encouraged to include as many of them as you possibly could, starting with the most relevant ones.  
You don't have to include the ones you are not using at all.  
Also, note that, once again, this list is non-exhaustive, at least for this version. Feel free to define the environment parameters you need.
