### ISSUE TITLE
Do we need a seperate "Trait Definiton File" ?

### ISSUE THREAD

**Issue by arendd** [MIAPPE/ISA-Tab-for-plant-phenotyping#7]
We currently try to adapt the new ISA-Configuration for MIAPPE 1.1 to some of our latest phenotyping experiments. 

First of all the initial draft and the comprehensive documentation is very good and helpful, I think the idea of splitting the assay due to the observation level hierarchy is a good solution and for many of our use cases very helpful. 

But I have some concerns about the idea to create separate “Trait Definition Files” for all samples in the “Phenotyping” protocol. Correct me, if I’m wrong, but there seems to be no connection between each sample (one line in the Assay file) and the “Trait Definition File”, like we have the “SampleName” for the “Study to Assay – Connection”. So this means, if I have 10.000 samples (and this is just a small experiment in our facility), we need also 10.000 “Trait Definition Files”, right?

Wouldn’t it be better and more efficient for machine-reading to just add the columns directly in the “Phenotyping” protocol in the Assay file due to the fact that the column structure is very similar and so at the end we also preserve the general ISA approach?

**Comment by PapoutsoglouE** [comment]
The trait definition file only holds the observed variables themselves, so there is no need to create more than one per investigation. Then, in your data file, you would include references to the ISA samples (MIAPPE observation unit) and extracts (MIAPPE sample). Each line should point to one sample/extract, but you can have multiple columns (with the variable ID in the header) to accommodate each variable evaluated.  
The `Parameter Value[Trait Definition File]` column in the assay file just indicates the name of the file where the variables are described, and can be (and in fact usually will) be the same across multiple lines.

I'm hope it's clearer now, but please let us know if there was a specific part in the documentation that created the misunderstanding that samples are linked/referred to in the tdf (or any point that could be improved, really)!

> Wouldn’t it be better and more efficient for machine-reading to just add the columns directly in the “Phenotyping” protocol in the Assay file due to the fact that the column structure is very similar and so at the end we also preserve the general ISA approach?

I am not sure what kind of columns you are talking about (for the variables?), let me know if this requires further clarification.

**Comment by proccaserra** [comment]
@arendd @PapoutsoglouE @hcwi @cpommier: if TDF is unique for a given trial, then it would beneficial to "normalise" a bit. I have just pushed a modified version of the investigation.xml configuration file which now bears  2 new fields in the STUDY definition section:
- line 172: "Comment[Trait Definition File]" -> to avoid unnecessary repetition of the information in the Assay file
- line 177: "Comment[Climatology Environment File]" -> this is a test using the similar approach in case you need to provide a link to a file holding meteorological information for the parcel or field use in the trials.

**Comment by arendd** [comment]
@proccaserra this is a good idea! 
Due to the size of our investigations, we are happy to avoid every redundant information to keep the metadata as clear as possible.

**Comment by proccaserra** [comment]
@arendd @PapoutsoglouE @cpommier @hcwi Do you have exemplar files for such 'climatology environmental / weather' files.
I have found the following reference (WUFI file: https://wufi.de/en/service/downloads/creating-weather-files/ and https://www.wufi-wiki.com/mediawiki/index.php/Details:Climate ) but it seems software specific and specific to the German National Meteorological Service.

I suspect each country will have its own format and we therefore may need to have an additional metadata element to report it.

**Comment by hcwi** [comment]
I am not aware of any specific climatology files, but from the experience with dealing plant phenotyping experiments and our previous approaches, the phenotypic traits and environmental variables have been treated equally: they are both observable variables, defined in some TDF files, whose observations are collected in data files. Importantly, it is sometimes difficult to distinguish what is a plant quality, what is an anvironment quality, or what is possible a combination of both, so managing them together has served us well.

**Comment by DanFaria** [comment]
I agree with @hcwi. Having a separate climatology file would go against the modeling option we made for MIAPPE 1.1. Observed "traits" should go into the same TDF, be they traits of the plant, of the soil, or of the weather.

**Comment by DanFaria** [comment]
I do agree that moving the TDF to the investigation file makes sense.

**Comment by PapoutsoglouE** [comment]
TDF has been added to the investigation in https://github.com/MIAPPE/ISA-Tab-for-plant-phenotyping/commit/b3b81da227c05a57771d64b33cc8dd11c699844b, and removed from the assay in https://github.com/MIAPPE/ISA-Tab-for-plant-phenotyping/commit/ccf86e6f8778530c36f6f473917c3f22da5e5bdf.
