### ISSUE TITLE
Is the Sampling protocol conform with the ISA format?

### ISSUE THREAD

**Issue by arendd** [MIAPPE/ISA-Tab-for-plant-phenotyping#8]
@proccaserra I have a question to the Sampling Protocol:
In the documentation you mentioned that this protocol has the Parameter Values "Sampling Date" and "Sampling Description", the column "Extract Name" and then two Characteristics "Plant Structure Development Stage" and "Plant Anatomical Entity". 

Does this mean that "Extract Name" and the both Characteristics belong to the Protocol "Sampling" ? 

I thought a "Protocol" can have only a list of "Parameter Values" ? 
Or is just the order of the columns important?

**Comment by PapoutsoglouE** [comment]
Maybe I can shed some light (as I'm primarily the one who composed the v1.1 readme, so you can blame me for not updating it...)

The Protocol in this case shows that a process has taken place (sampling), transforming a material from a Sample into an Extract. All material nodes (source, sample, extract) can have characteristics ([see ISA-Tab documentation](https://isa-specs.readthedocs.io/en/latest/isatab.html#assay-table-file) - I did not write this one), but I would not say that they "belong" to the protocol.

So yes, the order of the columns is important too. First the protocol with its parameters, then the extract name, then its characteristics. The order of the parameters and the characteristics among themselves is not important, but it's nice to keep it uniform. 

Note that changes are still being made to the ISA configuration, but they should be minor for the most part. You should be able to easily make the adjustments necessary (renaming/adding columns) when the time comes.

**Comment by arendd** [comment]
@PapoutsoglouE no need to worry. Thank you for clarify this and for your fast reply. I know the ISA-Tab documentation, but somehow I missed the section with the "Material Node", but I used the ISA-Tab Config files in parallel that’s why it was a bit confusing. Now I think it’s clear, but it would be maybe a good idea to add a point in the readme, what the “Sampling” Protocol means -> as you mentioned the process from taking an extract from a Sample, because this is not clear in the readme, at least for me…

So in my case it would means that I do not need the Sampling Protocol, because in summary I have a lot of plants, make a bunch of images within our phenotyping facility and then use an image analysis tool to determine a list of traits. So I never create an Extract as a part of my Samples or something like this. So I can leave the Protocol empty, right? But I have to provide the columns of the protocol anyway, because they are marked as “required=true”!?

**Comment by PapoutsoglouE** [comment]
Marking the Sampling protocol as required was a mistake. This will be fixed in the final configuration, sorry about the inconvenience!  

Yes, correct: you don't need samples in your case. You need to describe each observed variables that your imaging tool evaluates, and the details about the phenotyping facility and your process only have to be in the trait definition file. The sampling protocol and extract columns can be skipped altogether, but for now I guess you cannot do that inside the Creator.

I have also [added the clarification for the sampling in the readme](https://github.com/MIAPPE/ISA-Tab-for-plant-phenotyping/commit/c6c6809d331054bc3763d6bc706eb8ab0d0ac11e).

**Comment by PapoutsoglouE** [comment]
To be addressed in #14.
